// Template definition for "Booking" sheet — maps OrderCreateRQ XML to Excel columns

export const BOOKING_TEMPLATE = {
  sheetName: 'Booking',
  detectByRootElement: 'OrderCreateRQ',

  sectionHeaders: {
    3: 'FOP Details',
    12: 'Order Sales Information Accountable Documents Notification',
    13: 'Booking Qualifiers',
    17: 'Travelers Information',
    19: 'CR-18 Credit on Hold',
    21: 'SSR-1',
    27: 'SSR-2',
    33: 'SSR-3',
    39: 'SSR-4',
    45: 'OSI-1',
    50: 'OSI-2',
    55: 'OSI-3',
    60: 'OSI-4',
    65: 'OSI-5',
    70: 'PricingInfo Details',
    73: 'Remarks',
    74: 'TAX Exempt Options',
    77: 'ReportingData',
  },

  sectionMerges: [
    [3, 11], [12, 12], [13, 16], [17, 18], [19, 20],
    [21, 26], [27, 32], [33, 38], [39, 44],
    [45, 49], [50, 54], [55, 59], [60, 64], [65, 69],
    [70, 72], [73, 73], [74, 76], [77, 77],
  ],

  ndcColumns: [
    { col: 0, header: 'TestCase_ID', xpath: null, source: 'testCaseId' },
    { col: 1, header: 'OrderCreate_LongSell', xpath: null, extractor: 'conditionalY_LongSell' },
    { col: 2, header: 'PrimaryLangID', xpath: null },
    { col: 3, header: 'OrderCreate_FOP', xpath: null, extractor: 'mapFOP' },
    { col: 4, header: 'OrderCreate_Multiple_FOP', xpath: null },
    { col: 5, header: 'NA', xpath: null },
    { col: 6, header: 'Commission', xpath: null },
    { col: 7, header: 'Commission_Code', xpath: null },
    { col: 8, header: 'Commissions_Percentage_booking', xpath: null },
    { col: 9, header: 'OrderCreate_PaymentPlanCode', xpath: null },
    { col: 10, header: 'OrderCreate_Number_Of_Installments', xpath: null },
    { col: 11, header: 'OrderCreateExtendedPaymentCode', xpath: null },
    { col: 12, header: 'OrderCreate_OSIADN', xpath: null },
    { col: 13, header: 'NA', xpath: null },
    { col: 14, header: 'NA', xpath: null },
    { col: 15, header: 'NA', xpath: null },
    { col: 16, header: 'NA', xpath: null },
    { col: 17, header: 'OrderCreate_Traveler_IDs', xpath: null, extractor: 'listPassengerIDs_booking' },
    { col: 18, header: 'PaymentCardQualifiers_OrderCreate', xpath: null },
    { col: 19, header: 'WaiverCode_OrderCreate', xpath: null },
    { col: 20, header: 'TourCode_OrderCreate', xpath: null },
    { col: 21, header: 'SSR1_SSRCode', xpath: null },
    { col: 22, header: 'SSR1_TravelerRef', xpath: null },
    { col: 23, header: 'SSR1_SegmentRef', xpath: null },
    { col: 24, header: 'SSR1_AirlineCode', xpath: null },
    { col: 25, header: 'SSR1_ActionCode', xpath: null },
    { col: 26, header: 'SSR1_Text', xpath: null },
    { col: 27, header: 'SSR2_SSRCode', xpath: null },
    { col: 28, header: 'SSR2_TravelerRef', xpath: null },
    { col: 29, header: 'SSR2_SegmentRef', xpath: null },
    { col: 30, header: 'SSR2_AirlineCode', xpath: null },
    { col: 31, header: 'SSR2_ActionCode', xpath: null },
    { col: 32, header: 'SSR2_Text', xpath: null },
    { col: 33, header: 'SSR3_SSRCode', xpath: null },
    { col: 34, header: 'SSR3_TravelerRef', xpath: null },
    { col: 35, header: 'SSR3_SegmentRef', xpath: null },
    { col: 36, header: 'SSR3_AirlineCode', xpath: null },
    { col: 37, header: 'SSR3_ActionCode', xpath: null },
    { col: 38, header: 'SSR3_Text', xpath: null },
    { col: 39, header: 'SSR4_SSRCode', xpath: null },
    { col: 40, header: 'SSR4_TravelerRef', xpath: null },
    { col: 41, header: 'SSR4_SegmentRef', xpath: null },
    { col: 42, header: 'SSR4_AirlineCode', xpath: null },
    { col: 43, header: 'SSR4_ActionCode', xpath: null },
    { col: 44, header: 'SSR4_Text', xpath: null },
    { col: 45, header: 'OSI1_AirlineCode', xpath: null },
    { col: 46, header: 'OSI1_Text', xpath: null },
    { col: 47, header: 'OSI1_OSICode', xpath: null },
    { col: 48, header: 'OSI1_TravelerRef', xpath: null },
    { col: 49, header: 'OSI1_ActionCode', xpath: null },
    { col: 50, header: 'OSI2_AirlineCode', xpath: null },
    { col: 51, header: 'OSI2_Text', xpath: null },
    { col: 52, header: 'OSI2_OSICode', xpath: null },
    { col: 53, header: 'OSI2_TravelerRef', xpath: null },
    { col: 54, header: 'OSI2_ActionCode', xpath: null },
    { col: 55, header: 'OSI3_AirlineCode', xpath: null },
    { col: 56, header: 'OSI3_Text', xpath: null },
    { col: 57, header: 'OSI3_OSICode', xpath: null },
    { col: 58, header: 'OSI3_TravelerRef', xpath: null },
    { col: 59, header: 'OSI3_ActionCode', xpath: null },
    { col: 60, header: 'OSI4_AirlineCode', xpath: null },
    { col: 61, header: 'OSI4_Text', xpath: null },
    { col: 62, header: 'OSI4_OSICode', xpath: null },
    { col: 63, header: 'OSI4_TravelerRef', xpath: null },
    { col: 64, header: 'OSI4_ActionCode', xpath: null },
    { col: 65, header: 'OSI5_AirlineCode', xpath: null },
    { col: 66, header: 'OSI5_Text', xpath: null },
    { col: 67, header: 'OSI5_OSICode', xpath: null },
    { col: 68, header: 'OSI5_TravelerRef', xpath: null },
    { col: 69, header: 'OSI5_ActionCode', xpath: null },
    { col: 70, header: 'NA', xpath: null },
    { col: 71, header: 'NA', xpath: null },
    { col: 72, header: 'NA', xpath: null },
    { col: 73, header: 'Prebooking_GeneralRemark', xpath: null },
    { col: 74, header: 'TaxCode_Booking', xpath: null },
    { col: 75, header: 'TaxCountry_Booking', xpath: null },
    { col: 76, header: 'ExemptAll_Booking', xpath: null },
    { col: 77, header: 'OrderCreate_UatpReportingdata', xpath: null },
  ],

  flxColumns: [
    { col: 0, header: 'TestCase_ID', xpath: null, source: 'testCaseId' },
    { col: 1, header: 'NA', xpath: null },
    { col: 2, header: 'NA', xpath: null },
    { col: 3, header: 'PNRCreate_FOP', xpath: null, extractor: 'mapFOP' },
    { col: 4, header: 'PNRCreate_Multiple_FOP', xpath: null },
    { col: 5, header: 'InstallmentPayment_Months', xpath: null },
    { col: 13, header: 'PNRCreate_Qualifier_AirlineCode', xpath: null },
    { col: 14, header: 'PNRCreate_Corporate_ID', xpath: null },
    { col: 15, header: 'PNRCreate_Contract_ID', xpath: null },
    { col: 16, header: 'PNRCreate_Promo_Code', xpath: null },
    { col: 21, header: 'SSR1_SSRCode', xpath: null },
    { col: 22, header: 'SSR1_TravelerRef', xpath: null },
    { col: 23, header: 'SSR1_SegmentRef', xpath: null },
    { col: 24, header: 'SSR1_AirlineCode', xpath: null },
    { col: 26, header: 'SSR1_Text', xpath: null },
    { col: 27, header: 'SSR2_SSRCode', xpath: null },
    { col: 28, header: 'SSR2_TravelerRef', xpath: null },
    { col: 29, header: 'SSR2_SegmentRef', xpath: null },
    { col: 30, header: 'SSR2_AirlineCode', xpath: null },
    { col: 32, header: 'SSR2_Text', xpath: null },
    { col: 33, header: 'SSR3_SSRCode', xpath: null },
    { col: 34, header: 'SSR3_TravelerRef', xpath: null },
    { col: 35, header: 'SSR3_SegmentRef', xpath: null },
    { col: 36, header: 'SSR3_AirlineCode', xpath: null },
    { col: 38, header: 'SSR3_Text', xpath: null },
    { col: 39, header: 'SSR4_SSRCode', xpath: null },
    { col: 40, header: 'SSR4_TravelerRef', xpath: null },
    { col: 41, header: 'SSR4_SegmentRef', xpath: null },
    { col: 42, header: 'SSR4_AirlineCode', xpath: null },
    { col: 44, header: 'SSR4_Text', xpath: null },
    { col: 45, header: 'OSI1_AirlineCode', xpath: null },
    { col: 46, header: 'OSI1_Text', xpath: null },
    { col: 47, header: 'OSI1_OSICode', xpath: null },
    { col: 48, header: 'OSI1_TravelerRef', xpath: null },
    { col: 50, header: 'OSI2_AirlineCode', xpath: null },
    { col: 51, header: 'OSI2_Text', xpath: null },
    { col: 52, header: 'OSI2_OSICode', xpath: null },
    { col: 53, header: 'OSI2_TravelerRef', xpath: null },
    { col: 55, header: 'OSI3_AirlineCode', xpath: null },
    { col: 56, header: 'OSI3_Text', xpath: null },
    { col: 57, header: 'OSI3_OSICode', xpath: null },
    { col: 58, header: 'OSI3_TravelerRef', xpath: null },
    { col: 60, header: 'OSI4_AirlineCode', xpath: null },
    { col: 61, header: 'OSI4_Text', xpath: null },
    { col: 62, header: 'OSI4_OSICode', xpath: null },
    { col: 63, header: 'OSI4_TravelerRef', xpath: null },
    { col: 65, header: 'OSI5_AirlineCode', xpath: null },
    { col: 66, header: 'OSI5_Text', xpath: null },
    { col: 67, header: 'OSI5_OSICode', xpath: null },
    { col: 68, header: 'OSI5_TravelerRef', xpath: null },
    { col: 70, header: 'PricingInfo_Price', xpath: null },
    { col: 71, header: 'PricingInfo_StorePrice', xpath: null },
    { col: 72, header: 'PricingInfo_BestPricing', xpath: null },
  ],
};
