// Template definition for "Pricing" sheet — maps OfferPriceRQ XML to Excel columns

export const PRICING_TEMPLATE = {
  sheetName: 'Pricing',
  detectByRootElement: 'OfferPriceRQ',

  sectionHeaders: {
    2: 'OfferPrice Preferences / Filters',
    10: 'OfferPrice Qualifiers',
    17: 'OfferPrice Fare Options',
    18: '(CR-18) InExchangeForTicket / Previous OrderId / TC Reference',
    20: 'Redemption Flow',
    23: 'PriceClass Details For MultiCity',
    25: 'Delay Time',
    26: 'PriceByPAX',
    27: 'Augmentation Point',
  },

  sectionMerges: [
    [2, 9], [10, 16], [17, 17], [18, 19], [20, 22],
    [23, 24], [25, 25], [26, 26], [27, 28],
  ],

  ndcColumns: [
    { col: 0, header: 'TestCase_ID', xpath: null, source: 'testCaseId' },
    { col: 1, header: 'LongSell', xpath: null, extractor: 'conditionalY_LongSell' },
    { col: 2, header: 'OfferPrice_FareType', xpath: null },
    { col: 3, header: 'OfferPrice_Fare_PreferencesContext', xpath: null },
    { col: 4, header: 'Selector_UpsellOffers', xpath: null },
    { col: 5, header: 'OfferPrice_FareBasisCode_Preference', xpath: null },
    { col: 6, header: 'OfferPrice_BestPricing_Preference', xpath: null },
    { col: 7, header: 'OfferPrice_ServicePricing_Preference', xpath: null },
    { col: 8, header: 'OfferPrice_ServiceSelector', xpath: null },
    { col: 9, header: 'OfferPrice_ServicesEMDIssue_FOP', xpath: null },
    { col: 10, header: 'OfferPrice_Qualifier_AirlineID', xpath: null },
    { col: 11, header: 'OfferPrice_Corporate_ID', xpath: null },
    { col: 12, header: 'OfferPrice_Contract_ID', xpath: null },
    { col: 13, header: 'OfferPrice_Promo_Code', xpath: null },
    { col: 14, header: 'OfferPrice_CompanyIndex', xpath: null },
    { col: 15, header: 'OfferPrice_PaymentCardQualifiers', xpath: null },
    { col: 16, header: 'OfferPrice_MultiplePaymentCardQualifiers', xpath: null },
    { col: 17, header: 'OfferPrice_Exclusions', xpath: null },
    { col: 18, header: 'InExchangeForTicket', xpath: null },
    { col: 19, header: 'OrderId_TestCaseRef', xpath: null },
    { col: 20, header: 'NA', xpath: null },
    { col: 21, header: 'NA', xpath: null },
    { col: 22, header: 'NA', xpath: null },
    { col: 23, header: 'PriceClass_Name', xpath: null },
    { col: 24, header: 'PriceClass_Code', xpath: null },
    { col: 25, header: 'Delay_Pricing', xpath: null },
    { col: 26, header: 'Pricing_PriceByPax', xpath: null },
    { col: 27, header: 'CustomParamsName', xpath: null },
    { col: 28, header: 'CustomParamsValue', xpath: null },
  ],

  flxColumns: [
    { col: 0, header: 'TestCase_ID', xpath: null, source: 'testCaseId' },
    { col: 1, header: 'NA', xpath: null },
    { col: 2, header: 'FlightPrice_FareType', xpath: null },
    { col: 3, header: 'NA', xpath: null },
    { col: 4, header: 'NA', xpath: null },
    { col: 5, header: 'NA', xpath: null },
    { col: 6, header: 'FlightPrice_BestPricing_Preference', xpath: null },
    { col: 7, header: 'NA', xpath: null },
    { col: 8, header: 'NA', xpath: null },
    { col: 10, header: 'FlightPrice_Qualifier_AirlineCode', xpath: null },
    { col: 11, header: 'FlightPrice_Corporate_ID', xpath: null },
    { col: 12, header: 'FlightPrice_Contract_ID', xpath: null },
    { col: 13, header: 'FlightPrice_Promo_Code', xpath: null },
    { col: 17, header: 'FlightPrice_Exclusions', xpath: null },
    { col: 18, header: 'InExchangeForTicket', xpath: null },
    { col: 19, header: 'OrderId_TestCaseRef', xpath: null },
    { col: 20, header: 'CustomParams_Name', xpath: null },
    { col: 21, header: 'CustomParams_Value', xpath: null },
    { col: 22, header: 'SaleInfo_Channel', xpath: null },
    { col: 25, header: 'Delay_Pricing', xpath: null },
    { col: 26, header: 'Pricing_PriceByPax', xpath: null },
    { col: 27, header: 'CustomParamsName', xpath: null },
    { col: 28, header: 'CustomParamsValue', xpath: null },
  ],
};
