// Template definition for "Test Cases Data" sheet — maps AirShoppingRQ XML to Excel columns

export const TEST_CASES_DATA_TEMPLATE = {
  sheetName: 'Test Cases Data',
  detectByRootElement: 'AirShoppingRQ',

  // Row 0: Section group headers (col index → text)
  sectionHeaders: {
    12: 'Redemption Booking',
    13: 'CMPP Indicator',
    14: 'Origin Destination Details',
    26: 'Travelers Information',
    30: 'Flight Selection',
    34: 'FlightSpecific',
    35: 'Preferences / Filters',
    56: 'Fare Options',
    58: 'Qualifiers',
    66: 'MetaData',
    70: 'Stopover',
    73: 'Only FareSearch  - Branded Fares Support ',
    74: 'Departure / Arrival Filters FareSearch Only',
    80: 'FlightInformation Details',
    82: 'Flight Details for FareRules',
    84: 'Schedule Only',
    85: 'FareQuote Details',
    95: 'RouteList Details',
    100: 'Expected Error Message',
    102: 'Delay Time',
    103: 'Assertion support',
    110: 'TAX Exempt Options',
    114: 'PaymentFunctios',
    115: 'Assertion',
    116: 'Inbound/Outbound Ordinals',
    118: 'ResponseParameters',
  },

  // Row 0: Merged cell ranges [startCol, endCol]
  sectionMerges: [
    [12, 12], [13, 13], [14, 25], [26, 29], [30, 33], [34, 34],
    [35, 55], [56, 57], [58, 65], [66, 69], [70, 72],
    [73, 73], [74, 79], [80, 81], [82, 83], [84, 84],
    [85, 94], [95, 99], [100, 101], [102, 102], [103, 109],
    [110, 113], [114, 114], [115, 115], [116, 117], [118, 119],
  ],

  // NDC column definitions (Row 1)
  ndcColumns: [
    { col: 0, header: 'Active', xpath: null, defaultValue: 'Y' },
    { col: 1, header: 'TestCase_ID', xpath: null, source: 'testCaseId' },
    { col: 2, header: 'Functional_Area', xpath: null, defaultValue: 'NDC' },
    { col: 3, header: 'Scenario', xpath: null, source: 'userInput' },
    { col: 4, header: 'Environment_Name', xpath: null, source: 'userInput' },
    { col: 5, header: 'NDC_Version', xpath: '@Version' },
    { col: 6, header: 'Description', xpath: null, source: 'userInput' },
    { col: 7, header: 'PCC', xpath: 'Party/Sender/TravelAgencySender/PseudoCity' },
    { col: 8, header: 'PCC_SecondShopping', xpath: null },
    { col: 9, header: 'Bridged_PCC', xpath: null },
    { col: 10, header: 'AppSetting_Name', xpath: null },
    { col: 11, header: 'AppSetting_Value', xpath: null },
    { col: 12, header: 'Awards_Indicator', xpath: null },
    { col: 13, header: 'NA', xpath: null },
    { col: 14, header: 'Market', xpath: null, extractor: 'combineODs' },
    { col: 15, header: 'Market2', xpath: null, extractor: 'combineODs_2' },
    { col: 16, header: 'Market3', xpath: null, extractor: 'combineODs_3' },
    { col: 17, header: 'Market_SecondShopping', xpath: null },
    { col: 18, header: 'Market_Property', xpath: null },
    { col: 19, header: 'Travel_Dates', xpath: null, extractor: 'combineDates' },
    { col: 20, header: 'Travel_Dates2', xpath: null, extractor: 'combineDates_2' },
    { col: 21, header: 'Travel_Dates3', xpath: null, extractor: 'combineDates_3' },
    { col: 22, header: 'TravelDates_SecondShopping', xpath: null },
    { col: 23, header: 'Dep_Time_Preference', xpath: null, extractor: 'depTimePreference' },
    { col: 24, header: 'Arrival_Time_Preference', xpath: null, extractor: 'arrivalTimePreference' },
    { col: 25, header: 'CalendarDates', xpath: null },
    { col: 26, header: 'Travelers', xpath: null, extractor: 'countByPTC' },
    { col: 27, header: 'Traveler_IDs', xpath: null, extractor: 'listPassengerIDs' },
    { col: 28, header: 'Traveler_Details', xpath: null },
    { col: 29, header: 'Travelers_SecondShopping', xpath: null },
    { col: 30, header: 'FlightSelector', xpath: null, source: 'userInput' },
    { col: 31, header: 'FlightSelector_SecondShopping', xpath: null },
    { col: 32, header: 'FlightSelector_ThirdShopping', xpath: null },
    { col: 33, header: 'Cache_Shopping', xpath: null },
    { col: 34, header: 'FlightSpecific_Shopping', xpath: null },
    { col: 35, header: 'FareType', xpath: null, source: 'userInput' },
    { col: 36, header: 'FareType_Second_Shopping', xpath: null },
    { col: 37, header: 'FareBasisCode_Preference', xpath: null },
    { col: 38, header: 'FareBasisCode_PreferencesLevel', xpath: null },
    { col: 39, header: 'Airline_Preference', xpath: null },
    { col: 40, header: 'Airline_PreferencesLevel', xpath: null },
    { col: 41, header: 'CoS_Code', xpath: null },
    { col: 42, header: 'Cabin_Code', xpath: null },
    { col: 43, header: 'CabinCode_SecondShopping', xpath: null },
    { col: 44, header: 'Cabin_PrefLevelCode', xpath: null },
    { col: 45, header: 'Cabin_Name', xpath: null },
    { col: 46, header: 'BestPricingOptionText', xpath: null },
    { col: 47, header: 'BestPricingOptionText_SecondShopping', xpath: null },
    { col: 48, header: 'StationCriteria', xpath: null },
    { col: 49, header: 'StationCriteria_PrefLevelCode', xpath: null },
    { col: 50, header: 'Transfer_Preference_Include', xpath: null },
    { col: 51, header: 'Transfer_Preference_Exclude', xpath: null },
    { col: 52, header: 'Stops_Preference', xpath: null },
    { col: 53, header: 'Stops_PreferencesLevel', xpath: null },
    { col: 54, header: 'Min_Time', xpath: null },
    { col: 55, header: 'Max_Time', xpath: null },
    { col: 56, header: 'Exclusions', xpath: null },
    { col: 57, header: 'Ticket_Designator', xpath: null },
    { col: 58, header: 'Qualifier_AirlineID', xpath: null },
    { col: 59, header: 'Contract_ID', xpath: null },
    { col: 60, header: 'Qualifier_AirlineID_SecondShopping', xpath: null },
    { col: 61, header: 'Contract_ID_SecondShopping', xpath: null },
    { col: 62, header: 'Corporate_ID', xpath: null },
    { col: 63, header: 'Promo_Code', xpath: null },
    { col: 64, header: 'CompanyIndex', xpath: null },
    { col: 65, header: 'PaymentCardQualifiers', xpath: null },
    { col: 66, header: 'TourCode', xpath: null },
    { col: 67, header: 'Penalties_RuleMetadatas', xpath: null },
    { col: 68, header: 'RuleID_TwoStep', xpath: null },
    { col: 69, header: 'RuleID_TwoStep_SecondShopping', xpath: null },
    { col: 70, header: 'Stopover_AirportCode', xpath: null },
    { col: 71, header: 'Stopover_DepartureDate', xpath: null },
    { col: 72, header: 'Stopover_CarrierCode', xpath: null },
    { col: 100, header: 'TestForError', xpath: null, source: 'userInput' },
    { col: 101, header: 'TestForError_TestStepName', xpath: null },
    { col: 102, header: 'Delay_Shopping', xpath: null },
    { col: 103, header: 'ExpectedTaxes', xpath: null },
    { col: 104, header: 'Market_ForBrandConfig', xpath: null },
    { col: 105, header: 'Commissions_Percentage', xpath: null },
    { col: 106, header: 'Commissions_Amount', xpath: null },
    { col: 107, header: 'Route_Happy_Context', xpath: null },
    { col: 108, header: 'ReconcileInventory', xpath: null },
    { col: 109, header: 'ValidateTIVA', xpath: null },
    { col: 110, header: 'TaxCode', xpath: null },
    { col: 111, header: 'TaxCountry', xpath: null },
    { col: 112, header: 'ExemptAll', xpath: null },
    { col: 113, header: 'TaxCollectionPoint', xpath: null },
    { col: 114, header: 'Airshopping_FOP', xpath: null },
    { col: 115, header: 'TourCodeAndTicketDesig', xpath: null },
    { col: 116, header: 'Ordinal', xpath: null },
    { col: 117, header: 'MulitiCity_Ordinal', xpath: null },
    { col: 118, header: 'LangCode', xpath: null },
    { col: 119, header: 'CurCode', xpath: null },
  ],

  // FLX column definitions (Row 2)
  flxColumns: [
    { col: 0, header: 'Active', xpath: null, defaultValue: 'Y' },
    { col: 1, header: 'TestCase_ID', xpath: null, source: 'testCaseId' },
    { col: 2, header: 'Functional_Area', xpath: null, defaultValue: 'FLX' },
    { col: 3, header: 'Scenario', xpath: null, source: 'userInput' },
    { col: 4, header: 'Environment_Name', xpath: null, source: 'userInput' },
    { col: 5, header: 'NA', xpath: null },
    { col: 6, header: 'Description', xpath: null, source: 'userInput' },
    { col: 7, header: 'PCC', xpath: 'Party/Sender/TravelAgencySender/PseudoCity' },
    { col: 8, header: 'NA', xpath: null },
    { col: 9, header: 'Bridged_PCC', xpath: null },
    { col: 10, header: 'AppSetting_Name', xpath: null },
    { col: 11, header: 'AppSetting_Value', xpath: null },
    { col: 12, header: 'NA', xpath: null },
    { col: 13, header: 'CMPP_Flow', xpath: null, source: 'userInput' },
    { col: 14, header: 'Market', xpath: null, extractor: 'combineODs' },
    { col: 15, header: 'Market2', xpath: null, extractor: 'combineODs_2' },
    { col: 16, header: 'Market3', xpath: null, extractor: 'combineODs_3' },
    { col: 19, header: 'Travel_Dates', xpath: null, extractor: 'combineDates' },
    { col: 20, header: 'Travel_Dates2', xpath: null, extractor: 'combineDates_2' },
    { col: 21, header: 'Travel_Dates3', xpath: null, extractor: 'combineDates_3' },
    { col: 23, header: 'Dep_Time_Preference', xpath: null, extractor: 'depTimePreference' },
    { col: 24, header: 'Arrival_Time_Preference', xpath: null, extractor: 'arrivalTimePreference' },
    { col: 25, header: 'Window_Search', xpath: null },
    { col: 26, header: 'Travelers', xpath: null, extractor: 'countByPTC' },
    { col: 27, header: 'Traveler_IDs', xpath: null, extractor: 'listPassengerIDs' },
    { col: 30, header: 'FlightSelector', xpath: null, source: 'userInput' },
    { col: 35, header: 'FareType', xpath: null, source: 'userInput' },
    { col: 39, header: 'Airline_Preference', xpath: null },
    { col: 41, header: 'CoS_Code', xpath: null },
    { col: 42, header: 'Cabin_Code', xpath: null },
    { col: 50, header: 'Transfer_Preference_Include', xpath: null },
    { col: 51, header: 'Transfer_Preference_Exclude', xpath: null },
    { col: 52, header: 'FlightType', xpath: null },
    { col: 56, header: 'Exclusions', xpath: null },
    { col: 58, header: 'Qualifier_AirlineCode', xpath: null },
    { col: 59, header: 'Contract_ID', xpath: null },
    { col: 62, header: 'Corporate_ID', xpath: null },
    { col: 63, header: 'Promo_Code', xpath: null },
    { col: 73, header: 'BrandedFareSupport', xpath: null },
    { col: 74, header: 'Dep_Area', xpath: null },
    { col: 75, header: 'Dep_DistanceUnit', xpath: null },
    { col: 76, header: 'Dep_OtherCountries', xpath: null },
    { col: 77, header: 'Arrival_Area', xpath: null },
    { col: 78, header: 'Arrival_DistanceUnit', xpath: null },
    { col: 79, header: 'Arrival_OtherCountries', xpath: null },
    { col: 80, header: 'FlightInformation_BoundID', xpath: null },
    { col: 81, header: 'FlightInformation_SegmentID', xpath: null },
    { col: 82, header: 'FareRules_BoundID', xpath: null },
    { col: 83, header: 'FareRules_SegmentID', xpath: null },
    { col: 84, header: 'AirAvailability_ScheduleOnly', xpath: null },
    { col: 85, header: 'FareQuote_TripType', xpath: null },
    { col: 86, header: 'FareQuote_CoS_AirlineCode', xpath: null },
    { col: 87, header: 'FareQuote_CoS', xpath: null },
    { col: 88, header: 'FareQuote_CorporateCode', xpath: null },
    { col: 89, header: 'FareQuote_ContractCode', xpath: null },
    { col: 90, header: 'FareQuote_PromoCode', xpath: null },
    { col: 91, header: 'FareQuote_Cabin', xpath: null },
    { col: 92, header: 'FareQuote_Currency', xpath: null },
    { col: 93, header: 'FareQuote_TaxInclude', xpath: null },
    { col: 94, header: 'FareQuote_HistoricalPricingInfo_Date', xpath: null },
    { col: 95, header: 'RouteList_Carrier', xpath: null },
    { col: 96, header: 'RouteList_Airport', xpath: null },
    { col: 97, header: 'RouteList_Interline', xpath: null },
    { col: 98, header: 'RouteList_Flights', xpath: null },
    { col: 99, header: 'RouteList_Enhanced', xpath: null },
    { col: 100, header: 'TestForError', xpath: null, source: 'userInput' },
    { col: 101, header: 'TestForError_TestStepName', xpath: null },
    { col: 102, header: 'Delay_Shopping', xpath: null },
    { col: 103, header: 'ExpectedTaxes', xpath: null },
    { col: 105, header: 'Commissions_Percentage', xpath: null },
    { col: 106, header: 'Commissions_Amount', xpath: null },
    { col: 110, header: 'TaxCode', xpath: null },
    { col: 111, header: 'TaxCountry', xpath: null },
    { col: 112, header: 'ExemptAll', xpath: null },
    { col: 113, header: 'TaxCollectionPoint', xpath: null },
  ],
};
